### ISSUE TITLE
After adding custom javascript (js) function to timelion, Kibana stuck at Loading

### ISSUE THREAD

**Issue by tisage** [elastic/timelion#106]
Hello,

After reading the article:
https://www.elastic.co/blog/implementing-a-statistical-anomaly-detector-part-2 

I plan to add some common time-series functions to timelion. 

I follow the article's instruction:

1. Add js file under /kibana/installedPlugins/timelion/series_functions/
2. Remove timelion.bundle.js under /kibana/optimize/bundles/
3. Restart Kibana 

However, I got stuck at loading interface in Kibana.

Is there any way to rebuild optimize bundle appropriately? Why my Kibana stuck at loading interface?
I would appreciate if you could give some advice. 
Thank you very much.

**Comment by rashidkpc** [comment]
Remove all of /kibana/optimize/bundles and try that. Alternatively its possible its just taking a long time to rebuild

Last likelihood is that you have a typo, or the timelion's function format has changed since that blog post was written. I would recommend reading Kibana's CONTRIBUTING.md and setting up a dev environment instead of hacking on the built version of Kibana. The dev version will give you useful debug output in the console when something fails.
