### ISSUE TITLE
Error: in cell #1: `metric` requires metric:field or simply count

### ISSUE THREAD

**Issue by devoncrouse** [elastic/timelion#154]
After upgrading from Kibana 4.5.1->4.5.2, many of our Timelion expressions fail. Not seeing any documented changes to the syntax - am I missing something? Thanks!

Working:
```
.es(index='logstash_*')
```

Previously working; now produces error:
```
.es(index="logstash_*", metric="sum:value")
Error: in cell #1: `metric` requires metric:field or simply count
```

Previously working; now produces error:
```
.es(index="logstash_*", split="name:10")
Error: in cell #1: `split` requires field:limit
```

**Comment by ajviradia** [comment]
After upgrading from the 4.5.1 -> 4.5.3 yesterday, Timelion expressions are failing for us as well.

Interestingly, I found if the lucene query in the expression uses = instead of : , Timelion renders the graph for each character in the name of the field :( 

Expression : **es(index=app_logs-*,q="fields.ThreadId:9")**
get me following error:
![graph](https://cloud.githubusercontent.com/assets/5256834/16885236/7b5a8e5a-4a82-11e6-8012-7603ffc8d13f.png)

Timelion: Error: in cell #1: [query_parsing_exception] Failed to parse query [:], with: {"index":"app_logs-2016.07.15","line":1,"col":693}

Expression : **es(index=app_logs-*,q="fields.ThreadId=9")**
gets me a graph with series for f,i,e,l,d,s.......

**Comment by vineet-rh** [comment]
Getting the same error as @devoncrouse 
I tried @ajviradia's fix by trying metric='sum=<field_name>' but without luck.

**Comment by rashidkpc** [comment]
My bad, fixed here: https://github.com/elastic/timelion/commit/41f5acf193e44afacf36f6c9f3b9f3bf7feca993

**Comment by rashidkpc** [comment]
Also, now released

**Comment by devoncrouse** [comment]
👍 verified working for us; thanks again.
