### ISSUE TITLE
After Upgrade to 5.2.x Timelion page is blank

### ISSUE THREAD

**Issue by pawprint-net** [elastic/timelion#197]
This is a duplicate of Issue #12 to re-open the issue. That was never resolved and people are still commenting on the closed issue looking for some help.

The issue there seems to be the problem but none of the proposed fixes work with the 5.2 version so the primary question remains:

For someone stuck in this situation on the 5.2.x release - how does one fix it?

**Comment by valbuena** [comment]
Hi, I found a temporal solution:
I'm using docker-compose and elasticdump to create a predefined .kibana index. So I created a .kibana index with this mapping. 
curl -XPUT 'http://elasticsearch:9200/.kibana?pretty' -H 'Content-Type: application/json' -d'
{
"mappings" : {
"default" : {
"properties" : {
"hits" : { "type" : "integer" },
"version" : { "type" : "integer" }
}}}
}

This way when I insert data with elasticdump I don't have problems with hits and version fields, because they are pre-defined like integer type and they are not dynamically created like long.

**Comment by barryhatfield** [comment]
After my upgrades I also encountered blank page issues.
elasticsearch 2.4.0 -> 5.2.2
kibana 4.6.0 -> 5.2.2

To resolve my blank pages from integer and version:
curl -XPOST '${ELASTICSEARCH_HOST}/_reindex?pretty' -d'
{
  "source": {
    "index": ".kibana1"
  },
  "dest": {
    "index": ".kibana2"
  },
  "script": {
    "inline": "ctx._source.remove(\"version\")"
  }
}
'

and

curl -XPOST '${ELASTICSEARCH_HOST}/_reindex?pretty' -d'
{
  "source": {
    "index": ".kibana2"
  },
  "dest": {
    "index": ".kibana3"
  },
  "script": {
    "inline": "ctx._source.remove(\"hits\")"
  }
}
'

This resolved my blank pages in management and visualization (from another post):

curl -XPOST '${ELASTICSEARCH_HOST}/.kibana3/_update_by_query?pretty&wait_for_completion&refresh' -H 'Content-Type: application/json' -d'
{
  "script": {
    "inline": "ctx._source.defaultIndex = null",
    "lang": "painless"
  },
  "query": {
    "term": {
      "_type": "config"
    }
  }
}
'

Finally, be sure to update your .kibana index in your kibana/config/kibana.yml to .kibana3. You can always rollback to .kibana if you like.

**Comment by tbragin** [comment]
@sbaker-gsc  Timelion is now part of Kibana. Could you file this issue in https://github.com/elastic/kibana/issues ?
